# docker compose up -d
# docker compose down
services:
  solr:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
      - ./web.xml:/opt/solr/server/solr-webapp/webapp/WEB-INF/web.xml:ro
    command:
      - solr-precreate
      - interim-index

volumes:
  data:
